java_binary(
    name = "JaclynDevSandbox",
    main_class = "dev.jaclyn.sandbox.base.SandboxServer",
    srcs = [],
    runtime_deps = [
        "@jooby//:org_jooby_jooby_jetty",
        "//modules/sandbox-main/src/main/java/dev/jaclyn/sandbox/base"
    ],
)