java_binary(
    name = "JaclynDevSandbox",
    main_class = "src/main/java/dev/jaclyn/sandbox/base/SandboxServer.java",
    srcs = glob(["src/main/java/dev/jaclyn/sandbox/*.java"]),
    runtime_deps = [
        "@jooby//:org_jooby_jooby_jetty",
    ]
)